title: Manuel Mees # your name (or website title) here
logo: "---" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Maschinenbauingenieur Fachrichtung Industrielle Produktion
  <br><br>
  <a href="mailto:manuel.mees@gmail.com">manuel.mees@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/manuel-mees-3667a1156/">LinkedIn Profile</a>
  <br>
  //<a href="https://www.gihub.com/aashimaahuja/">Gihub</a>
